# This Dockerfile builds a binary for use with the QuickPiperAudiobook command.
# It can be used for testing or for architectures that don't have a Piper build.
# docker build -t quickpiperaudiobook .
# docker run quickpiperaudiobook /app/examples/lorem_ipsum.txt

FROM golang:1.22 AS build

WORKDIR /app

COPY . .

# Install Go dependencies and build the binary
RUN go mod tidy && \
    go build -o QuickPiperAudiobook .

FROM fedora:latest

# Install runtime dependencies
RUN dnf install -y \
    # needed for ebook-convert
    calibre \
    ffmpeg \
    && dnf clean all

WORKDIR /app

# Copy the binary
COPY --from=build /app/QuickPiperAudiobook .

# Set the command to run the binary, allowing an argument for the file
ENTRYPOINT ["./QuickPiperAudiobook"]
# Allow passing arguments from CLI; mount a file if needed, or point to a remote URL
CMD []
